name: Teste API Postman

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  test:
    name: Testes API
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
          collection: [aLogin, Cadastro, Editar, Excluir, Listar]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Copiando os arquivos para maquina virtual
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Etapa 01 - Verificação versão do Node e Newman
        run: |
          newman --version && node --version && ls
              
      # Runs a single command using the runners shell
      - name: Etapa 02 - Html Extra Reporter
        run: |
          npm fund
          npm install -g newman
          sudo npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-merge 
    
    # Rodando as Collections de Testes
      - name: Rodando a Collection aLogin
        run: |
          newman run aLogin_collection.json -e postman_environment.json --reporters json --reporter-json-export results/aLogin.json
  
      - name: Rodando a Collection Cadastro
        run: |
          newman run Cadastro_collection.json -e postman_environment.json --reporters json --reporter-json-export results/Cadastro.json
  
      - name: Rodando a Collection Editar
        run: |
          newman run Editar_collection.json -e postman_environment.json --reporters json --reporter-json-export results/Editar.json
    
      - name: Rodando a Collection Excluir
        run: |
          newman run Excluir_collection.json -e postman_environment.json --reporters json --reporter-json-export results/Excluir.json
    
      - name: Rodando a Collection Listar
        run: |
          newman run Listar_collection.json -e postman_environment.json --reporters json --reporter-json-export results/Listar.json
      
      - name: Merge JSON results
        run: |
          npx newman-reporter-merge --sources results/aLogin.json results/Cadastro.json results/Editar.json results/Excluir.json results/Listar.json --output results/merged-result.json
    
      - name: Generate consolidated HTML report
        run: |
          newman run aLogin.postman_collection.json --reporters htmlextra --reporter-htmlextra-export results/merged-result.html --reporter-htmlextra-title "Teste API Postman" --reporter-htmlextra-jsonExport results/merged-result.json     
      
    
  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    if: always()
    needs: 
    - test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://naracyntia.github.io/Qualitys-Hunters-academy-api-com-postman/Report.html
    
    steps:
     - name: Setup Pages
       uses: actions/configure-pages@v5

     - name: Download Artifacts
       uses: actions/download-artifact@v4
       with: 
        name: report 

     - name: Upload artifact
       uses: actions/upload-pages-artifact@v3
       with:
        path: ./result1   
              ./result2
              ./result3
              ./result4 
              ./result5

     - name: Deploy to Github Pages
       id: deployment
       uses: actions/deploy-pages@v4      