name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Newman and reporters
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Run Newman tests for collections aLogin
      run: |
        mkdir -p results
        newman run path/to/your/aLogin.postman_collection.json -e "postman_enviroment.json" --delay-request 1 --reporters cli --reporter-htmlextra-displayProgressBar, -r htmlextra --reporter-htmlextra-export ./result/Report.html results/aLogin.json
     
    - name: Run Newman tests for collections Cadastro
      run: |
        mkdir -p results  
        newman run path/to/your/Cadastro.postman_collection.json -e "postman_enviroment.json" --delay-request 1 --reporters cli --reporter-htmlextra-displayProgressBar, -r htmlextra --reporter-htmlextra-export ./result/Report.html results/aLogin.json
    
    - name: Run Newman tests for collections Editar
      run: |
        mkdir -p results
        newman run path/to/your/Editar.postman_collection.json -e "postman_enviroment.json" --delay-request 1 --reporters cli --reporter-htmlextra-displayProgressBar, -r htmlextra --reporter-htmlextra-export ./result/Report.html results/aLogin.json
    
    - name: Run Newman tests for collections Excluir
      run: |
        mkdir -p results
        newman run path/to/your/Excluir.postman_collection.json -e "postman_enviroment.json" --delay-request 1 --reporters cli --reporter-htmlextra-displayProgressBar, -r htmlextra --reporter-htmlextra-export ./result/Report.html results/aLogin.json
     
    - name: Run Newman tests for collections Listar
      run: |
        mkdir -p results
        newman run path/to/your/Listar.postman_collection.json -e "postman_enviroment.json" --delay-request 1 --reporters cli --reporter-htmlextra-displayProgressBar, -r htmlextra --reporter-htmlextra-export ./result/Report.html results/aLogin.json

    - name: Merge JSON results
      run: |
        node merge-results.js

    - name: Generate consolidated HTML report
      run: |
        newman run path/to/your/aLogin.postman_collection.json --reporters htmlextra --reporter-htmlextra-export results/index.html --reporter-htmlextra-title "Consolidated Test Report" --reporter-htmlextra-jsonExport results/merged-result.json

  deploy:
      name: Deploy GitHub Pages 🌐
      runs-on: ubuntu-latest
      if: always()
      needs: 
       - test
      permissions:
        contents: read
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: https://naracyntia.github.io/Qualitys-Hunters-academy-api-com-postman/Report.html
    
      steps:
        - name: Setup Pages
          uses: actions/configure-pages@v5
      
        - name: Download Artifacts
          uses: actions/download-artifact@v4
          with: 
            name: report
      
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: ./
      
        - name: Deploy to Github Pages
          id: deployment
          uses: actions/deploy-pages@v4

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./results